### PR TITLE
transformed KDClass into templated class for easy integration with PC…

### PR DESCRIPTION
**Pull request by Marcus-Davi**
transformed KDClass into templated class for easy integration with PCL and custom point types. All external struct and classes have been moved inside KDTree class for uniformization

I've also changed the demo.cpp to conform with new usage. My next intention is to write a PCL wrapper to use as a PCL::Search object

### CODE REVIEW

**Comment by Ecstasy-EC** [comment]
Hi! @Marcus-Davi 
Many thanks to your contribution. I will check your pull requests later since I have been busy these days.

**Comment by Ecstasy-EC** [comment]
@Marcus-Davi  Nice work! I have already merged your pull request to the main branch.

**Comment by Ecstasy-EC** [comment]
@Marcus-Davi 
Hi! Would you please send me your email address? We got some private issue that have to communicate with you.

**Comment by Marcus-Davi** [comment]
@Ecstasy-EC sure! davi2812@dee.ufc.br

**Pull request merged**
