### PR TITLE
Separate includes files and example files / Add additional, visualized examples / Elaborate README.md

### PR DESCRIPTION
**Pull request by LimHyungTae**
Dear @Ecstasy-EC:

Hello there Yixi, I'd like to do PR to your ikd-tree repository. Your fantastic method deserves to be nicer!

[Features]
* Separate includes files and example files
* Add two examples (Also, I follow your code format...In fact I hate your combination format of the Snake case and Pascal case  lol)
    * In particular, the public function `Search_Points_by_box` is added. Please refer to codes.
* Update README
    * In particular, build commands are added
    * Visualized results are added

As you're an HKUSTian, so I utilized livox-loam to get the Red Bird Sundial pcd file :smile: 

In addition, my `large_scale_map.pcd` is used for an example 3, i.e., the async example. I think this file can be substituted by any file. If you'd like to use this file, it would also be better to upload `large_scale_map.pcd` on your lab's official drive (e.g. Google drive). If then, please README.md appropriately!

Cheers~

### CODE REVIEW

**Comment by Ecstasy-EC** [comment]
Hello HyungTae,

Thanks for your great contributions! I have gone through your commits and all of them seem OK to be merged. I will make further tests and merge them next week before I upgrade the codes.

Btw, I am a HKUian but not HKUSTian though I am very very familiar with HKUST lol.

Cheers!

**Comment by Ecstasy-EC** [comment]
Hey @LimHyungTae !
Your codes are running well and everything looks fine. But I got one question. What are the files in `/.idea`? I found them not related to any codes and everything works fine after deleting them. If they are not required by any codes, I will remove them before I merge your pull request.

**Comment by LimHyungTae** [comment]
Oh, it is a kind of .vscode folder, which is not necessary to run codes. Please remove the '.idea'. Thank you bro I hope to see you at ICRA'22~~ :)

**Comment by Ecstasy-EC** [comment]
@LimHyungTae 
OK I got it. Gonna merge it tomorrow and move forward to the new version.  Thanks a lot for your contributions bro! 

And unfortunately, I won't appear in the ICRA 2022 since the ikd-tree was not submitted to it. It was integrated and submitted to a journal together with FAST-LIO2(link in my README). Anyway, best wishes to you and your research!

**Pull request merged**
